# -*- coding: utf-8 -*-
"""CSV FILE ANALYSIS

Arranges output data from a CSV file generated by "Oxy-Gen" software
on a given GEDCOM file
"""

import pandas as pd

keep_dict = {
    'OXG_ID_INDIVIDU'  : 'id_indi',
    'OXG_ID_FATHER'    : 'id_dad',
    'OXG_ID_MOTHER'    : 'id_mom',
    'OXG_PARTNER'      : 'id_spouse',
    'OXG_ID_PATRONYME' : 'surname',
    'OXG_GIVNAME'      : 'firstname',
    'OXG_Sex'          : 'sex',
	 }

df = pd.read_csv('./test3_familytreebeard/descend_familytreebeard.csv')



df = df[list(keep_dict.keys())]


def remove_unneeded_columns(df, list_of_columns_to_keep):
    df_simple = df['','','','']
    return df



columns_list = list(remove_dict.values())

